# Generated by Django 5.0 on 2024-01-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='masjed',
            field=models.IntegerField(choices=[(1, 'الحسنين'), (2, 'السلام'), (3, 'القزاز')], default=1, verbose_name='المسجد'),
        ),
    ]
