# Generated by Django 5.0 on 2024-03-16 17:48

import students.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_student_parts_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='q_elite_test',
            field=models.JSONField(default=students.utils.json_default_value_60, verbose_name='السبر النوعي في المسجد'),
        ),
    ]
