# Generated by Django 5.0 on 2024-03-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_student_q_elite_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='masjed',
            field=models.IntegerField(choices=[(1, 'الحسنين'), (2, 'السلام'), (3, 'القزاز')], verbose_name='المسجد'),
        ),
    ]
