# Generated by Django 5.0 on 2024-04-26 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_student_masjed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorizenotes',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memo_notes', to='students.student', verbose_name='اسم الطالب'),
        ),
    ]
