# Generated by Django 5.0 on 2024-09-01 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_memorizenotes_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorizemessage',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='اسم الأستاذ'),
        ),
        migrations.AlterField(
            model_name='memorizemessage',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.student', verbose_name='اسم الطالب'),
        ),
        migrations.AlterField(
            model_name='memorizenotes',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الأستاذ'),
        ),
        migrations.AlterField(
            model_name='memorizenotes',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memo_notes', to='students.student', verbose_name='اسم الطالب'),
        ),
    ]
