# Generated by Django 5.0 on 2024-09-14 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_alter_student_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mother_name',
            field=models.CharField(max_length=30, null=True, verbose_name='اسم الأم'),
        ),
    ]
