# Generated by Django 5.0 on 2025-03-01 00:22

import students.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_alter_memorizemessage_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='q_elite_test',
            field=models.JSONField(default=students.utils.json_default_value_60, verbose_name='سبر الأحزاب في المسجد'),
        ),
    ]
