# Generated by Django 5.2.11 on 2026-05-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_alter_student_q_elite_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='masjed',
            field=models.IntegerField(choices=[(1, 'الحسنين'), (2, 'السلام'), (3, 'القزاز'), (4, 'الخنساء')], verbose_name='المسجد'),
        ),
    ]
