# Generated by Django 5.2.11 on 2026-05-26 16:24

import students.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_alter_student_masjed'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='q_viewing',
            field=models.JSONField(default=students.utils.json_default_value_618, verbose_name='سرد القرآن نظراً'),
        ),
        migrations.AlterField(
            model_name='memorizemessage',
            name='message_type',
            field=models.IntegerField(choices=[(1, 'تسميع'), (2, 'سبر'), (3, 'أربعين نووية'), (4, 'رياض الصالحين'), (5, 'أسماء الله الحسنى'), (6, 'سبر الأحزاب'), (7, 'سرد نظراً'), (8, 'كنوز من السنة')], default=1, verbose_name='نوع الرسالة'),
        ),
    ]
