# Generated by Django 5.2.11 on 2026-06-01 11:37

import students.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_student_q_viewing_alter_memorizemessage_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorizemessage',
            name='message_type',
            field=models.IntegerField(choices=[(1, 'تسميع'), (2, 'سبر'), (3, 'أربعين نووية'), (4, 'رياض الصالحين'), (5, 'أسماء الله الحسنى'), (6, 'سبر الأحزاب'), (7, 'قراءة نظراً'), (8, 'كنوز من السنة')], default=1, verbose_name='نوع الرسالة'),
        ),
        migrations.AlterField(
            model_name='student',
            name='q_viewing',
            field=models.JSONField(default=students.utils.json_default_value_618, verbose_name='قراءة القرآن نظراً'),
        ),
    ]
