# Generated by Django 5.2.11 on 2026-06-01 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_alter_memorizemessage_message_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='extra_hadeeth',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50)], verbose_name='كنوز من السنة'),
        ),
    ]
