# Generated by Django 5.0 on 2024-12-13 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0016_remove_student_unique__name__mother_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizzQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='نص السؤال')),
                ('level', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third')], verbose_name='مستوى السؤال')),
                ('right_choice', models.TextField(verbose_name='الاختيار الصحيح')),
                ('wrong_choice1', models.TextField(verbose_name='اختيار خاطئ 1')),
                ('wrong_choice2', models.TextField(verbose_name='اختيار خاطئ 2')),
                ('wrong_choice3', models.TextField(verbose_name='اختيار خاطئ 3')),
            ],
            options={
                'verbose_name': 'سؤال اختبار',
                'verbose_name_plural': 'أسئلة الاختبارات',
            },
        ),
        migrations.CreateModel(
            name='QuizzSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='الاسم')),
            ],
            options={
                'verbose_name': 'مادة اختبار',
                'verbose_name_plural': 'مواد الاختبارات',
            },
        ),
        migrations.CreateModel(
            name='QuizzAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=6, verbose_name='كلمة المرور')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'حساب اختبار',
                'verbose_name_plural': 'حسابات اختبارات',
            },
        ),
        migrations.CreateModel(
            name='PassedQuizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third')], verbose_name='مستوى السؤال')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quizz.quizzaccount', verbose_name='الحساب')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quizz.quizzsubject', verbose_name='المادة')),
            ],
            options={
                'verbose_name': 'اختبار ناجح',
                'verbose_name_plural': 'اختبارات ناجحة',
            },
        ),
    ]
