# Generated by Django 5.0 on 2025-01-01 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0002_quizzaccount_session'),
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzaccount',
            name='session',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.session'),
        ),
    ]
