# Generated by Django 5.0 on 2025-01-02 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0003_alter_quizzaccount_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzquestion',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quizz.quizzsubject'),
            preserve_default=False,
        ),
    ]
