# Generated by Django 5.0 on 2024-01-05 14:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsAddingCause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='الاسم')),
            ],
            options={
                'verbose_name': 'سبب إضافة',
                'verbose_name_plural': 'أسباب الإضافة',
            },
        ),
        migrations.CreateModel(
            name='PointsDeletingCause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='الاسم')),
            ],
            options={
                'verbose_name': 'سبب حذف',
                'verbose_name_plural': 'أسباب الحذف',
            },
        ),
        migrations.CreateModel(
            name='PointsAdding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='القيمة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='اسم الأستاذ')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='الطالب')),
                ('cause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='points.pointsaddingcause', verbose_name='السبب')),
            ],
            options={
                'verbose_name': 'إضافة نقاط',
                'verbose_name_plural': 'إضافات النقاط',
            },
        ),
        migrations.CreateModel(
            name='PointsDeleting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='القيمة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='اسم الأستاذ')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='الطالب')),
                ('cause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='points.pointsdeletingcause', verbose_name='السبب')),
            ],
            options={
                'verbose_name': 'حذف نقاط',
                'verbose_name_plural': 'حذف النقاط',
            },
        ),
    ]
