# Generated by Django 5.0 on 2024-01-27 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coming',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comings.comingcategory', verbose_name='سبب الحضور'),
        ),
    ]
