export * from './table/table.component';
export * from './table/table.component.interface';
export * from './view/view.component';
export * from './view/view.component.interface';
export * from './create/create.component';
export * from './create/create.component.interface';
export * from './student-search/student-search.component';
export * from './student-search/search-student.interface';
export * from './changes-field/changes-field.component';
