# Generated by Django 5.0 on 2024-01-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('double_points', models.BooleanField(default=False, verbose_name='مضاعفة النقاط')),
                ('point_value', models.IntegerField(verbose_name='قيمة النقطة')),
                ('event_title', models.CharField(max_length=511, null=True, verbose_name='عنوان الحدث')),
                ('hidden_ids', models.JSONField(default=list, verbose_name='المعرفات المخفية')),
            ],
        ),
    ]
