# Generated by Django 5.0 on 2024-01-05 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwqafTestNoQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='الاسم')),
                ('points', models.IntegerField(verbose_name='النقاط')),
            ],
            options={
                'verbose_name': 'سبر أوقاف بغير القرآن',
                'verbose_name_plural': 'سبر الأوقاف بغير القرآن',
            },
        ),
        migrations.CreateModel(
            name='AwqafNoQStudentRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_old', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awqaf.awqaftestnoq')),
            ],
            options={
                'unique_together': {('test', 'student')},
            },
        ),
    ]
