# Generated by Django 5.0 on 2024-04-13 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awqaf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='awqafnoqstudentrelation',
            options={'verbose_name': 'سبر الطالب بالأوقاف بغير القرآن', 'verbose_name_plural': 'سبر الطلاب بالأوقاف بغير القرآن'},
        ),
    ]
