# Generated by Django 5.0 on 2024-09-01 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awqaf', '0002_alter_awqafnoqstudentrelation_options'),
        ('students', '0011_alter_memorizemessage_master_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awqafnoqstudentrelation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.student'),
        ),
        migrations.AlterField(
            model_name='awqafnoqstudentrelation',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='awqaf.awqaftestnoq'),
        ),
    ]
