/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */

export interface AddAwqafTestNoQRequestSerailizer {
  students: number[];
  test: number;
}
