/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */
import type { MasjedEnum } from './masjed-enum';

export interface AddMoneyDeletingCategoryRequestSerailizer {
  category: number;
  cause: number;
  value: number;
  masjed: MasjedEnum;
}
