/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `normal` - normal
 * * `looking` - looking
 * * `explaining` - explaining
 */
export type AddAwqafTestQRequestType =
  (typeof AddAwqafTestQRequestType)[keyof typeof AddAwqafTestQRequestType];

export const AddAwqafTestQRequestType = {
  normal: 'normal',
  looking: 'looking',
  explaining: 'explaining',
} as const;
