/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */
import type { AddAwqafTestQRequestType } from './addAwqafTestQRequestType';

export interface AddAwqafTestQRequest {
  students: number[];
  /**
     * * `normal` - normal
     * * `looking` - looking
     * * `explaining` - explaining
     */
  type: AddAwqafTestQRequestType;
  /**
     * @items.minimum 0
     * @items.maximum 29
     */
  parts: number[];
}
