/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */

export interface AddEliteTest {
  student: number;
  /**
     * @items.minimum 0
     * @items.maximum 59
     */
  parts: number[];
}
