/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */
import type { MasjedEnum } from './masjed-enum';
import type { StudentLevelEnum } from './student-level-enum';

export interface AdminStudentList {
  id: number;
  /** @maxLength 80 */
  name: string;
  /**
   * @maxLength 30
   * @nullable
   */
  mother_name?: string | null;
  masjed: MasjedEnum;
  level?: StudentLevelEnum;
  /** @nullable */
  category?: number | null;
  /** @nullable */
  group?: number | null;
  readonly registered_at: string;
}
