/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */
import type { MasjedEnum } from './masjedEnum';

export type AdminGlobalsNewsListParams = {
/**
 * عدد النتائج التي يجب إرجاعها في كل صفحة.
 */
limit?: number;
/**
 * * `1` - الحسنين
 * * `2` - السلام
 * * `3` - القزاز
 * * `4` - الخنساء
 */
masjed?: MasjedEnum;
/**
 * الفهرس الأولي الذي يجب البدء منه لإرجاع النتائج.
 */
offset?: number;
/**
 * أي حقل يجب استخدامه عند ترتيب النتائج.
 */
ordering?: string;
};
