/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */

export interface AdminComingList {
  id: number;
  readonly registered_at: string;
  is_doubled?: boolean;
  /** @nullable */
  master?: number | null;
  student: number;
  student_name: string;
  category: number;
}
