/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */

export type AdminExtraTotalMoneyListParams = {
/**
 * عدد النتائج التي يجب إرجاعها في كل صفحة.
 */
limit?: number;
/**
 * الفهرس الأولي الذي يجب البدء منه لإرجاع النتائج.
 */
offset?: number;
/**
 * أي حقل يجب استخدامه عند ترتيب النتائج.
 */
ordering?: string;
};
