/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */
import type { MasjedEnum } from './masjed-enum';
import type { MessageTypeEnum } from './message-type-enum';
import type { StudentLevelEnum } from './student-level-enum';

export type AdminStudentsMemorizeMessageListParams = {
  is_doubled?: boolean;
  /**
   * عدد النتائج التي يجب إرجاعها في كل صفحة.
   */
  limit?: number;
  master?: number;
  master__isnull?: boolean;
  /**
   * * `1` - تسميع
   * * `2` - سبر
   * * `3` - أربعين نووية
   * * `4` - رياض الصالحين
   * * `5` - أسماء الله الحسنى
   * * `6` - سبر الأحزاب
   * * `7` - قراءة نظراً
   * * `8` - كنوز من السنة
   */
  message_type?: MessageTypeEnum;
  /**
   * الفهرس الأولي الذي يجب البدء منه لإرجاع النتائج.
   */
  offset?: number;
  /**
   * أي حقل يجب استخدامه عند ترتيب النتائج.
   */
  ordering?: string;
  sended_at__date?: string;
  sended_at__gt?: string;
  sended_at__lt?: string;
  /**
   * * `1` - الحسنين
   * * `2` - السلام
   * * `3` - القزاز
   * * `4` - الخنساء
   */
  student__masjed?: MasjedEnum;
  /**
   * param for filtering result via student name or student id
   */
  student__name?: string;
  /**
   * * `1` - مستوى أول
   * * `2` - مستوى ثاني
   * * `3` - مستوى ثالث
   */
  student_level?: StudentLevelEnum;
};
