/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */
import type { MasjedEnum } from './masjed-enum';
import type { StudentLevelEnum } from './student-level-enum';

export type AdminStudentsStudentListParams = {
  category?: number;
  category__isnull?: boolean;
  group?: number;
  group__isnull?: boolean;
  /**
   * * `1` - مستوى أول
   * * `2` - مستوى ثاني
   * * `3` - مستوى ثالث
   */
  level?: StudentLevelEnum;
  /**
   * عدد النتائج التي يجب إرجاعها في كل صفحة.
   */
  limit?: number;
  /**
   * * `1` - الحسنين
   * * `2` - السلام
   * * `3` - القزاز
   * * `4` - الخنساء
   */
  masjed?: MasjedEnum;
  /**
   * param for filtering student via his name or his id
   */
  name?: string;
  /**
   * الفهرس الأولي الذي يجب البدء منه لإرجاع النتائج.
   */
  offset?: number;
  /**
   * أي حقل يجب استخدامه عند ترتيب النتائج.
   */
  ordering?: string;
  registered_at?: string;
  registered_at__gt?: string;
  registered_at__lt?: string;
};
