/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */
import type { MasjedEnum } from './masjedEnum';

export type AdminStudentsMemorizeNotesListParams = {
/**
 * عدد النتائج التي يجب إرجاعها في كل صفحة.
 */
limit?: number;
master?: number;
master__isnull?: boolean;
/**
 * الفهرس الأولي الذي يجب البدء منه لإرجاع النتائج.
 */
offset?: number;
/**
 * أي حقل يجب استخدامه عند ترتيب النتائج.
 */
ordering?: string;
sended_at?: string;
sended_at__gt?: string;
sended_at__lt?: string;
/**
 * * `1` - الحسنين
 * * `2` - السلام
 * * `3` - القزاز
 * * `4` - الخنساء
 */
student__masjed?: MasjedEnum;
/**
 * param for filtering result via student name or student id
 */
student__name?: string;
};
