/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminPointsaddingList } from './adminPointsaddingList';

export interface AdminPaginatedpointsaddingListlist {
  count: number;
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results: AdminPointsaddingList[];
}
