/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */
import type { AssetFile } from './assetFile';

export interface AssetCategory {
  readonly id: number;
  files: AssetFile[];
  /** @maxLength 255 */
  name: string;
}
