/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */

export interface AssetFileCreate {
  /** @maxLength 255 */
  name: string;
  file: string;
  category: number;
}
