/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */

export interface AwqafRelation {
  readonly id: number;
  is_old?: boolean;
  test: number;
}
