/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */

export interface AwqafNoQStudentRelationList {
  id: number;
  student: number;
  student_name: string;
  test: number;
  is_old?: boolean;
}
