/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */

export interface ComingListForStudent {
  readonly id: number;
  readonly registered_at: string;
}
