/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */

export interface ComingCategoryCreate {
  /** @maxLength 40 */
  name: string;
  /**
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  points?: number;
}
