/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */
import type { MasjedEnum } from './masjed-enum';

export type ComingsListParams = {
  category?: number;
  /**
   * رقم الصفحة ضمن النتائج المقسمة.
   */
  page?: number;
  registered_at__gt?: string;
  registered_at__lt?: string;
  /**
   * * `1` - الحسنين
   * * `2` - السلام
   * * `3` - القزاز
   * * `4` - الخنساء
   */
  student__masjed?: MasjedEnum;
};
