/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */

export interface ComingList {
  readonly id: number;
  student: string;
  masjed: number;
  readonly registered_at: string;
  category: number;
}
