/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */

export interface ControlSettings {
  double_points?: boolean;
  /**
     * @minimum -9223372036854776000
     * @maximum 9223372036854776000
     */
  point_value: number;
  /**
     * @maxLength 511
     * @nullable
     */
  event_title?: string | null;
  hidden_ids?: unknown;
}
