/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */

export type MasjedEnum = typeof MasjedEnum[keyof typeof MasjedEnum];


export const MasjedEnum = {
  HASANIN: 1,
  SALAM: 2,
  QAZZAZ: 3,
  KHANSAA: 4,
} as const;
