/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */

export interface MemorizeNotesGet {
  readonly id: number;
  /** @maxLength 60 */
  content: string;
  readonly sended_at: string;
}
