/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */
import type { MasjedEnum } from './masjed-enum';
import type { MessageTypeEnum } from './message-type-enum';
import type { StudentLevelEnum } from './student-level-enum';

export interface MemorizeMessage {
  readonly id: number;
  student: string;
  masjed: MasjedEnum;
  message_type: MessageTypeEnum;
  changes?: number[];
  readonly sended_at: string;
  student_level: StudentLevelEnum;
}
