/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */

export interface MemorizeNotesList {
  id: number;
  /** @maxLength 60 */
  content: string;
  student: number;
  student_name: string;
  /** @nullable */
  master?: number | null;
  readonly sended_at: string;
}
