/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */
import type { MessageTypeEnum } from './message-type-enum';

export interface MemorizeMessageForStudent {
  readonly id: number;
  message_type?: MessageTypeEnum;
  changes?: number[];
}
