/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */
import type { MessageTypeEnum } from './message-type-enum';
import type { StudentLevelEnum } from './student-level-enum';

export interface MemorizeMessageList {
  id: number;
  /** @nullable */
  master?: number | null;
  student: number;
  student_name: string;
  readonly sended_at: string;
  changes?: unknown;
  message_type?: MessageTypeEnum;
  is_doubled?: boolean;
  student_level: StudentLevelEnum;
}
