/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */

export interface MoneyDeletingList {
  id: number;
  readonly created_at: string;
  active_to_points?: boolean;
  /**
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  value: number;
  student: number;
  student_name: string;
  cause: number;
}
