/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */
import type { MasjedEnum } from './masjed-enum';

export interface NewsCreate {
  /** @maxLength 255 */
  title: string;
  /** @nullable */
  description?: string | null;
  low_quality_image: string;
  main_image: string;
  masjed: MasjedEnum;
}
