/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */
import type { StudentListWithComingRegistration } from './student-list-with-coming-registration';

export interface PaginatedStudentListWithComingRegistrationList {
  count: number;
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results: StudentListWithComingRegistration[];
}
