/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */

export interface PointsDeletingList {
  id: number;
  student: number;
  student_name: string;
  /** @nullable */
  master?: number | null;
  readonly created_at: string;
  /** @nullable */
  cause?: number | null;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  value: number;
}
