/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */
import type { MasjedEnum } from './masjedEnum';

export interface PointsAddingList {
  readonly id: number;
  student: string;
  masjed: MasjedEnum;
  /**
     * @minimum 0
     * @maximum 9223372036854776000
     */
  value: number;
  readonly created_at: string;
  cause: number;
}
