/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */

export interface PointsAddingCreate {
  students: number[];
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  value: number;
  cause: number;
}
