/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */

export type ReportsCategoryCreateParams = {
/**
 * param for determining if the response is excel file or not
 */
excel?: boolean;
};
