/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */

export interface ReportsStudentCategoryOrGroupStudent {
  student_id: number;
  student_name: string;
  sum_memo: number;
  sum_test: number;
  sum_viewing: number;
  sum_elite_test: number;
  sum_extra_hadeeth: number;
  sum_all: number;
}
