/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */
import type { ReportsStudentCategoryOrGroupStudent } from './reports-student-category-or-group-student';

export interface ReportsStudentCategoryOrGroupResponse {
  students: ReportsStudentCategoryOrGroupStudent[];
  total_memo: number;
  total_test: number;
  total_viewing: number;
  total_elite_test: number;
  total_extra_hadeeth: number;
  total: number;
}
