/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */
import type { ReportMemorizeMessage } from './reportMemorizeMessage';

export interface ReportsStudentResponse {
  messages: ReportMemorizeMessage[];
  sum_memo: number;
  sum_test: number;
  sum_viewing: number;
  sum_elite_test: number;
  sum_extra_hadeeth: number;
  sum_all: number;
}
