/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */

export interface StatisticsRequest {
  start_date?: string;
  end_date?: string;
  memo?: boolean;
  test?: boolean;
  awqaf_test?: boolean;
  awqaf_test_looking?: boolean;
  awqaf_test_explaining?: boolean;
  active_students?: boolean;
}
