/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */

export interface StatisticsResponse {
  memo?: number[];
  test?: number[];
  awqaf_test?: number[];
  awqaf_test_looking?: number[];
  awqaf_test_explaining?: number[];
  active_students?: number[];
}
