/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */
import type { MasjedEnum } from './masjedEnum';
import type { StudentCategory } from './studentCategory';
import type { StudentGroup } from './studentGroup';

export interface StudentList {
  readonly id: number;
  /** @maxLength 80 */
  name: string;
  category: StudentCategory | null;
  group: StudentGroup | null;
  /**
     * @maxLength 30
     * @nullable
     */
  mother_name?: string | null;
  /** @nullable */
  birthdate?: string | null;
  /**
     * @maxLength 50
     * @nullable
     */
  parts_received?: string | null;
  masjed: MasjedEnum;
}
