/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */

export interface StudentUpdateQTest {
  /**
     * @items.minimum 0
     * @items.maximum 239
     */
  q_test: number[];
}
