/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */

export interface StudentCategoryUpdate {
  /** @maxLength 40 */
  name: string;
}
