/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */

export type StudentLevelEnum = typeof StudentLevelEnum[keyof typeof StudentLevelEnum];


export const StudentLevelEnum = {
  ONE: 1,
  TWO: 2,
  THREE: 3,
} as const;
