/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */

export interface StudentUpdateQMemo {
  /**
   * @items.minimum 0
   * @items.maximum 617
   */
  q_memo: number[];
}
