/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */
import type { MasjedEnum } from './masjed-enum';
import type { StudentCategory } from './student-category';
import type { StudentGroup } from './student-group';

export interface StudentListWithComingRegistration {
  readonly id: number;
  /** @maxLength 80 */
  name: string;
  category: StudentCategory | null;
  group: StudentGroup | null;
  /**
   * @maxLength 30
   * @nullable
   */
  mother_name?: string | null;
  /** @nullable */
  birthdate?: string | null;
  masjed: MasjedEnum;
  is_registered_today: boolean;
}
