/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */
import type { AwqafRelation } from './awqafRelation';
import type { ComingListForStudent } from './comingListForStudent';
import type { MasjedEnum } from './masjedEnum';
import type { MemorizeMessageForStudent } from './memorizeMessageForStudent';
import type { MemorizeNotesGet } from './memorizeNotesGet';
import type { StudentCategory } from './studentCategory';
import type { StudentGroup } from './studentGroup';
import type { StudentLevelEnum } from './studentLevelEnum';

export interface StudentDetails {
  readonly id: number;
  level: StudentLevelEnum;
  category: StudentCategory | null;
  group: StudentGroup | null;
  memo_notes: MemorizeNotesGet[];
  awqaf_relations: AwqafRelation[];
  last_comings: ComingListForStudent[];
  previous_week_messages: MemorizeMessageForStudent[];
  current_week_messages: MemorizeMessageForStudent[];
  first_half_month_messages: MemorizeMessageForStudent[];
  second_half_month_messages: MemorizeMessageForStudent[];
  current_date: string;
  /** @maxLength 80 */
  name: string;
  /**
     * @maxLength 30
     * @nullable
     */
  mother_name?: string | null;
  /** @nullable */
  birthdate?: string | null;
  /**
     * @maxLength 80
     * @nullable
     */
  address?: string | null;
  /**
     * @maxLength 10
     * @nullable
     */
  static_phone?: string | null;
  /**
     * @maxLength 25
     * @nullable
     */
  cell_phone?: string | null;
  /**
     * @maxLength 25
     * @nullable
     */
  father_phone?: string | null;
  /**
     * @maxLength 25
     * @nullable
     */
  mother_phone?: string | null;
  readonly registered_at: string;
  /**
     * @maxLength 80
     * @nullable
     */
  father_work?: string | null;
  /**
     * @maxLength 60
     * @nullable
     */
  notes?: string | null;
  /**
     * @maxLength 80
     * @nullable
     */
  bring_him?: string | null;
  /**
     * @maxLength 50
     * @nullable
     */
  parts_received?: string | null;
  q_memorizing?: unknown;
  q_test?: unknown;
  q_elite_test?: unknown;
  q_viewing?: unknown;
  q_awqaf_test?: unknown;
  q_awqaf_test_looking?: unknown;
  q_awqaf_test_explaining?: unknown;
  /**
     * @minimum 0
     * @maximum 50
     */
  alarbaein_alnawawia_old?: number;
  /**
     * @minimum 0
     * @maximum 50
     */
  alarbaein_alnawawia_new?: number;
  /**
     * @minimum 0
     * @maximum 9223372036854776000
     */
  riad_alsaalihin_old?: number;
  /**
     * @minimum 0
     * @maximum 9223372036854776000
     */
  riad_alsaalihin_new?: number;
  allah_names_old?: boolean;
  allah_names_new?: boolean;
  /**
     * @minimum 0
     * @maximum 50
     */
  extra_hadeeth?: number;
  masjed: MasjedEnum;
}
