/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */
import type { MasjedEnum } from './masjed-enum';
import type { StudentLevelEnum } from './student-level-enum';

export interface StudentUpdate {
  /** @maxLength 80 */
  name: string;
  /**
   * @maxLength 30
   * @nullable
   */
  mother_name?: string | null;
  /** @nullable */
  birthdate?: string | null;
  /**
   * @maxLength 80
   * @nullable
   */
  address?: string | null;
  /**
   * @maxLength 10
   * @nullable
   */
  static_phone?: string | null;
  /**
   * @maxLength 25
   * @nullable
   */
  cell_phone?: string | null;
  /**
   * @maxLength 25
   * @nullable
   */
  father_phone?: string | null;
  /**
   * @maxLength 25
   * @nullable
   */
  mother_phone?: string | null;
  /**
   * @maxLength 80
   * @nullable
   */
  father_work?: string | null;
  /**
   * @maxLength 60
   * @nullable
   */
  notes?: string | null;
  /**
   * @maxLength 80
   * @nullable
   */
  bring_him?: string | null;
  /**
   * @maxLength 50
   * @nullable
   */
  parts_received?: string | null;
  q_viewing?: unknown;
  /**
   * @minimum 0
   * @maximum 50
   */
  alarbaein_alnawawia_old?: number;
  /**
   * @minimum 0
   * @maximum 50
   */
  alarbaein_alnawawia_new?: number;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  riad_alsaalihin_old?: number;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  riad_alsaalihin_new?: number;
  allah_names_old?: boolean;
  allah_names_new?: boolean;
  /**
   * @minimum 0
   * @maximum 50
   */
  extra_hadeeth?: number;
  masjed: MasjedEnum;
  level?: StudentLevelEnum;
  /** @nullable */
  category?: number | null;
  /** @nullable */
  group?: number | null;
}
