/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */

export type StudentsListParams = {
  /**
   * رقم الصفحة ضمن النتائج المقسمة.
   */
  page?: number;
  /**
   * param for filtering result via student name or student id
   */
  query?: string;
};
