/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */

export interface TokenObtainPair {
  username: string;
  password: string;
  readonly access: string;
  readonly refresh: string;
}
