/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */

export interface UserUpdatePassword {
  user: number;
  /**
     * @minLength 1
     * @maxLength 128
     */
  new_password: string;
}
