# Generated by Django 5.0 on 2024-01-05 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
            ],
            options={
                'verbose_name': 'فئة ملفات',
                'verbose_name_plural': 'فئات الملفات',
            },
        ),
        migrations.CreateModel(
            name='AssetFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('file', models.FileField(upload_to='assets', verbose_name='الملف')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='globals.assetscategory', verbose_name='الفئة')),
            ],
            options={
                'verbose_name': 'ملف للتحميل',
                'verbose_name_plural': 'ملفات للتحميل',
            },
        ),
    ]
