# Generated by Django 5.0 on 2025-05-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0002_alter_assetfile_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='الاسم')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('low_quality_image', models.ImageField(upload_to='news_low_quality', verbose_name='صورة بدقة منخفضة')),
                ('main_image', models.ImageField(upload_to='news_main', verbose_name='الصورة الرئيسية')),
                ('masjed', models.IntegerField(choices=[(1, 'الحسنين'), (2, 'السلام'), (3, 'القزاز')])),
            ],
            options={
                'verbose_name': 'إعلان',
                'verbose_name_plural': 'إعلانات',
            },
        ),
    ]
