# Generated by Django 5.2.11 on 2026-05-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0003_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='masjed',
            field=models.IntegerField(choices=[(1, 'الحسنين'), (2, 'السلام'), (3, 'القزاز'), (4, 'الخنساء')]),
        ),
    ]
