# Generated by Django 5.0 on 2024-09-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0003_alter_pointsadding_master_alter_pointsadding_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsaddingcause',
            name='maximum_limit',
            field=models.IntegerField(default=100, verbose_name='حد الإضافة الأعلى'),
            preserve_default=False,
        ),
    ]
