/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient,
  HttpHeaders,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  TokenObtainPair,
  TokenRefresh,
  UserSerilizer
} from './models';




// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;


interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};







@Injectable({ providedIn: 'root' })
export class AccountsService {
  private readonly http = inject(HttpClient);
 accountsDetailsRetrieve<TData = UserSerilizer>( options?: HttpClientBodyOptions): Observable<TData>;
 accountsDetailsRetrieve<TData = UserSerilizer>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 accountsDetailsRetrieve<TData = UserSerilizer>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  accountsDetailsRetrieve<TData = UserSerilizer>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/v1/accounts/details`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/v1/accounts/details`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/v1/accounts/details`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * Takes a set of user credentials and returns an access and refresh JSON web
 * token pair to prove the authentication of those credentials.
 */
 accountsTokenCreate<TData = TokenObtainPair>(tokenObtainPair: NonReadonly<TokenObtainPair>, options?: HttpClientBodyOptions): Observable<TData>;
 accountsTokenCreate<TData = TokenObtainPair>(tokenObtainPair: NonReadonly<TokenObtainPair>, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 accountsTokenCreate<TData = TokenObtainPair>(tokenObtainPair: NonReadonly<TokenObtainPair>, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  accountsTokenCreate<TData = TokenObtainPair>(
    tokenObtainPair: NonReadonly<TokenObtainPair>, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/v1/accounts/token`,
      tokenObtainPair,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/v1/accounts/token`,
      tokenObtainPair,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/v1/accounts/token`,
      tokenObtainPair,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * Takes a refresh type JSON web token and returns an access type JSON web
 * token if the refresh token is valid.
 */
 accountsTokenRefreshCreate<TData = TokenRefresh>(tokenRefresh: NonReadonly<TokenRefresh>, options?: HttpClientBodyOptions): Observable<TData>;
 accountsTokenRefreshCreate<TData = TokenRefresh>(tokenRefresh: NonReadonly<TokenRefresh>, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 accountsTokenRefreshCreate<TData = TokenRefresh>(tokenRefresh: NonReadonly<TokenRefresh>, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  accountsTokenRefreshCreate<TData = TokenRefresh>(
    tokenRefresh: NonReadonly<TokenRefresh>, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/v1/accounts/token/refresh`,
      tokenRefresh,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/v1/accounts/token/refresh`,
      tokenRefresh,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/v1/accounts/token/refresh`,
      tokenRefresh,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
};

export type AccountsDetailsRetrieveClientResult = NonNullable<UserSerilizer>
export type AccountsTokenCreateClientResult = NonNullable<TokenObtainPair>
export type AccountsTokenRefreshCreateClientResult = NonNullable<TokenRefresh>
