/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient,
  HttpHeaders,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  AdminAuthGroupListParams,
  GroupCreate,
  GroupList,
  GroupUpdate,
  IdsAction
} from './models';




interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};

type AngularHttpParamValue = string | number | boolean | Array<string | number | boolean>;
type AngularHttpParamValueWithNullable = AngularHttpParamValue | null;

function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys?: ReadonlySet<string>,
  preserveRequiredNullables?: false,
  passthroughKeys?: undefined,
): Record<string, AngularHttpParamValue>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> | undefined,
  preserveRequiredNullables: true,
  passthroughKeys?: undefined,
): Record<string, AngularHttpParamValueWithNullable>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> | undefined,
  preserveRequiredNullables: boolean | undefined,
  passthroughKeys: ReadonlySet<string>,
): Record<string, unknown>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> = new Set(),
  preserveRequiredNullables = false,
  passthroughKeys: ReadonlySet<string> = new Set(),
): Record<string, unknown> {
  const filteredParams: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(params)) {
    if (passthroughKeys.has(key)) {
      if (value !== undefined) {
        filteredParams[key] = value;
      }
      continue;
    }
    if (Array.isArray(value)) {
      const filtered = value.filter(
        (item) =>
          item != null &&
          (typeof item === 'string' ||
            typeof item === 'number' ||
            typeof item === 'boolean'),
      ) as Array<string | number | boolean>;
      if (filtered.length) {
        filteredParams[key] = filtered;
      }
    } else if (value === null && requiredNullableKeys.has(key)) {
      // With a paramsSerializer (preserveRequiredNullables) the literal null
      // is passed through for it to consume; without one, emit an empty
      // string so the required key still reaches the wire as `?key=`
      // instead of being silently dropped. See #3712.
      filteredParams[key] = preserveRequiredNullables ? null : '';
    } else if (
      value != null &&
      (typeof value === 'string' ||
        typeof value === 'number' ||
        typeof value === 'boolean')
    ) {
      filteredParams[key] = value;
    }
  }
  return filteredParams;
}





@Injectable({ providedIn: 'root' })
export class AdminGroupService {
  private readonly http = inject(HttpClient);
 adminActionsGroupDeleteCreate<TData = void>(idsAction: IdsAction, options?: HttpClientBodyOptions): Observable<TData>;
 adminActionsGroupDeleteCreate<TData = void>(idsAction: IdsAction, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 adminActionsGroupDeleteCreate<TData = void>(idsAction: IdsAction, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  adminActionsGroupDeleteCreate<TData = void>(
    idsAction: IdsAction, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/v1/admin/actions/group/delete`,
      idsAction,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/v1/admin/actions/group/delete`,
      idsAction,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/v1/admin/actions/group/delete`,
      idsAction,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * A base class that inherit from `ModelViewSet` applying
 * django filter package filters and ordering filter
 */
 adminAuthGroupList<TData = GroupList[]>(params?: AdminAuthGroupListParams, options?: HttpClientBodyOptions): Observable<TData>;
 adminAuthGroupList<TData = GroupList[]>(params?: AdminAuthGroupListParams, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 adminAuthGroupList<TData = GroupList[]>(params?: AdminAuthGroupListParams, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  adminAuthGroupList<TData = GroupList[]>(
    params?: AdminAuthGroupListParams, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    const filteredParams = filterParams({...params, ...options?.params}, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/v1/admin/auth/group/`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,}
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/v1/admin/auth/group/`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,}
    );
    }

    return this.http.get<TData>(
      `/api/v1/admin/auth/group/`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
        params: filteredParams,}
    );
  }
/**
 * A base class that inherit from `ModelViewSet` applying
 * django filter package filters and ordering filter
 */
 adminAuthGroupCreate<TData = GroupCreate>(groupCreate: GroupCreate, options?: HttpClientBodyOptions): Observable<TData>;
 adminAuthGroupCreate<TData = GroupCreate>(groupCreate: GroupCreate, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 adminAuthGroupCreate<TData = GroupCreate>(groupCreate: GroupCreate, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  adminAuthGroupCreate<TData = GroupCreate>(
    groupCreate: GroupCreate, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/v1/admin/auth/group/`,
      groupCreate,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/v1/admin/auth/group/`,
      groupCreate,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/v1/admin/auth/group/`,
      groupCreate,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * A base class that inherit from `ModelViewSet` applying
 * django filter package filters and ordering filter
 */
 adminAuthGroupRetrieve<TData = GroupList>(id: number, options?: HttpClientBodyOptions): Observable<TData>;
 adminAuthGroupRetrieve<TData = GroupList>(id: number, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 adminAuthGroupRetrieve<TData = GroupList>(id: number, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  adminAuthGroupRetrieve<TData = GroupList>(
    id: number, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/v1/admin/auth/group/${id}/`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/v1/admin/auth/group/${id}/`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/v1/admin/auth/group/${id}/`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * A base class that inherit from `ModelViewSet` applying
 * django filter package filters and ordering filter
 */
 adminAuthGroupUpdate<TData = GroupUpdate>(id: number,
    groupUpdate: GroupUpdate, options?: HttpClientBodyOptions): Observable<TData>;
 adminAuthGroupUpdate<TData = GroupUpdate>(id: number,
    groupUpdate: GroupUpdate, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 adminAuthGroupUpdate<TData = GroupUpdate>(id: number,
    groupUpdate: GroupUpdate, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  adminAuthGroupUpdate<TData = GroupUpdate>(
    id: number,
    groupUpdate: GroupUpdate, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.put<TData>(
      `/api/v1/admin/auth/group/${id}/`,
      groupUpdate,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.put<TData>(
      `/api/v1/admin/auth/group/${id}/`,
      groupUpdate,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.put<TData>(
      `/api/v1/admin/auth/group/${id}/`,
      groupUpdate,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * A base class that inherit from `ModelViewSet` applying
 * django filter package filters and ordering filter
 */
 adminAuthGroupDestroy<TData = void>(id: number, options?: HttpClientBodyOptions): Observable<TData>;
 adminAuthGroupDestroy<TData = void>(id: number, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 adminAuthGroupDestroy<TData = void>(id: number, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  adminAuthGroupDestroy<TData = void>(
    id: number, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/v1/admin/auth/group/${id}/`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/v1/admin/auth/group/${id}/`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/v1/admin/auth/group/${id}/`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
};

