/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */
import { HttpClient, HttpHeaders, HttpResponse as AngularHttpResponse } from '@angular/common/http';
import type { HttpContext, HttpEvent, HttpParams } from '@angular/common/http';

import { Injectable, inject } from '@angular/core';

import { Observable } from 'rxjs';

import { API_BASE_URL } from './api.base-url';

import type { ControlSettings } from './models';

interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
    HttpParams | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: { includeHeaders?: string[] } | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};

@Injectable({ providedIn: 'root' })
export class AdminSettingsService {
  private readonly http = inject(HttpClient);
  private readonly baseUrl = inject(API_BASE_URL);
  adminExtraControlSettingsRetrieve<TData = ControlSettings>(
    options?: HttpClientBodyOptions,
  ): Observable<TData>;
  adminExtraControlSettingsRetrieve<TData = ControlSettings>(
    options?: HttpClientEventOptions,
  ): Observable<HttpEvent<TData>>;
  adminExtraControlSettingsRetrieve<TData = ControlSettings>(
    options?: HttpClientResponseOptions,
  ): Observable<AngularHttpResponse<TData>>;
  adminExtraControlSettingsRetrieve<TData = ControlSettings>(
    options?: HttpClientObserveOptions,
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(`${this.baseUrl}/api/v1/admin/extra/control-settings`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      });
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(`${this.baseUrl}/api/v1/admin/extra/control-settings`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      });
    }

    return this.http.get<TData>(`${this.baseUrl}/api/v1/admin/extra/control-settings`, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body',
    });
  }
  adminExtraControlSettingsUpdate<TData = void>(
    controlSettings: ControlSettings,
    options?: HttpClientBodyOptions,
  ): Observable<TData>;
  adminExtraControlSettingsUpdate<TData = void>(
    controlSettings: ControlSettings,
    options?: HttpClientEventOptions,
  ): Observable<HttpEvent<TData>>;
  adminExtraControlSettingsUpdate<TData = void>(
    controlSettings: ControlSettings,
    options?: HttpClientResponseOptions,
  ): Observable<AngularHttpResponse<TData>>;
  adminExtraControlSettingsUpdate<TData = void>(
    controlSettings: ControlSettings,
    options?: HttpClientObserveOptions,
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.put<TData>(
        `${this.baseUrl}/api/v1/admin/extra/control-settings`,
        controlSettings,
        {
          ...(options as Omit<NonNullable<typeof options>, 'observe'>),
          observe: 'events',
        },
      );
    }

    if (options?.observe === 'response') {
      return this.http.put<TData>(
        `${this.baseUrl}/api/v1/admin/extra/control-settings`,
        controlSettings,
        {
          ...(options as Omit<NonNullable<typeof options>, 'observe'>),
          observe: 'response',
        },
      );
    }

    return this.http.put<TData>(
      `${this.baseUrl}/api/v1/admin/extra/control-settings`,
      controlSettings,
      {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      },
    );
  }
}
