/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient,
  HttpHeaders,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  AdminStudentsGroupListParams,
  IdsAction,
  StudentGroupCreate,
  StudentGroupList,
  StudentGroupUpdate
} from './models';




interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};

type AngularHttpParamValue = string | number | boolean | Array<string | number | boolean>;
type AngularHttpParamValueWithNullable = AngularHttpParamValue | null;

function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys?: ReadonlySet<string>,
  preserveRequiredNullables?: false,
  passthroughKeys?: undefined,
): Record<string, AngularHttpParamValue>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> | undefined,
  preserveRequiredNullables: true,
  passthroughKeys?: undefined,
): Record<string, AngularHttpParamValueWithNullable>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> | undefined,
  preserveRequiredNullables: boolean | undefined,
  passthroughKeys: ReadonlySet<string>,
): Record<string, unknown>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> = new Set(),
  preserveRequiredNullables = false,
  passthroughKeys: ReadonlySet<string> = new Set(),
): Record<string, unknown> {
  const filteredParams: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(params)) {
    if (passthroughKeys.has(key)) {
      if (value !== undefined) {
        filteredParams[key] = value;
      }
      continue;
    }
    if (Array.isArray(value)) {
      const filtered = value.filter(
        (item) =>
          item != null &&
          (typeof item === 'string' ||
            typeof item === 'number' ||
            typeof item === 'boolean'),
      ) as Array<string | number | boolean>;
      if (filtered.length) {
        filteredParams[key] = filtered;
      }
    } else if (value === null && requiredNullableKeys.has(key)) {
      // With a paramsSerializer (preserveRequiredNullables) the literal null
      // is passed through for it to consume; without one, emit an empty
      // string so the required key still reaches the wire as `?key=`
      // instead of being silently dropped. See #3712.
      filteredParams[key] = preserveRequiredNullables ? null : '';
    } else if (
      value != null &&
      (typeof value === 'string' ||
        typeof value === 'number' ||
        typeof value === 'boolean')
    ) {
      filteredParams[key] = value;
    }
  }
  return filteredParams;
}





@Injectable({ providedIn: 'root' })
export class AdminStudentGroupService {
  private readonly http = inject(HttpClient);
 adminActionsStudentGroupDeleteCreate<TData = void>(idsAction: IdsAction, options?: HttpClientBodyOptions): Observable<TData>;
 adminActionsStudentGroupDeleteCreate<TData = void>(idsAction: IdsAction, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 adminActionsStudentGroupDeleteCreate<TData = void>(idsAction: IdsAction, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  adminActionsStudentGroupDeleteCreate<TData = void>(
    idsAction: IdsAction, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/v1/admin/actions/student-group/delete`,
      idsAction,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/v1/admin/actions/student-group/delete`,
      idsAction,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/v1/admin/actions/student-group/delete`,
      idsAction,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * A base class that inherit from `ModelViewSet` applying
 * django filter package filters and ordering filter
 */
 adminStudentsGroupList<TData = StudentGroupList[]>(params?: AdminStudentsGroupListParams, options?: HttpClientBodyOptions): Observable<TData>;
 adminStudentsGroupList<TData = StudentGroupList[]>(params?: AdminStudentsGroupListParams, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 adminStudentsGroupList<TData = StudentGroupList[]>(params?: AdminStudentsGroupListParams, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  adminStudentsGroupList<TData = StudentGroupList[]>(
    params?: AdminStudentsGroupListParams, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    const filteredParams = filterParams({...params, ...options?.params}, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/v1/admin/students/group/`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,}
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/v1/admin/students/group/`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,}
    );
    }

    return this.http.get<TData>(
      `/api/v1/admin/students/group/`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
        params: filteredParams,}
    );
  }
/**
 * A base class that inherit from `ModelViewSet` applying
 * django filter package filters and ordering filter
 */
 adminStudentsGroupCreate<TData = StudentGroupCreate>(studentGroupCreate: StudentGroupCreate, options?: HttpClientBodyOptions): Observable<TData>;
 adminStudentsGroupCreate<TData = StudentGroupCreate>(studentGroupCreate: StudentGroupCreate, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 adminStudentsGroupCreate<TData = StudentGroupCreate>(studentGroupCreate: StudentGroupCreate, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  adminStudentsGroupCreate<TData = StudentGroupCreate>(
    studentGroupCreate: StudentGroupCreate, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/v1/admin/students/group/`,
      studentGroupCreate,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/v1/admin/students/group/`,
      studentGroupCreate,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/v1/admin/students/group/`,
      studentGroupCreate,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * A base class that inherit from `ModelViewSet` applying
 * django filter package filters and ordering filter
 */
 adminStudentsGroupRetrieve<TData = StudentGroupList>(id: number, options?: HttpClientBodyOptions): Observable<TData>;
 adminStudentsGroupRetrieve<TData = StudentGroupList>(id: number, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 adminStudentsGroupRetrieve<TData = StudentGroupList>(id: number, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  adminStudentsGroupRetrieve<TData = StudentGroupList>(
    id: number, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/v1/admin/students/group/${id}/`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/v1/admin/students/group/${id}/`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/v1/admin/students/group/${id}/`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * A base class that inherit from `ModelViewSet` applying
 * django filter package filters and ordering filter
 */
 adminStudentsGroupUpdate<TData = StudentGroupUpdate>(id: number,
    studentGroupUpdate: StudentGroupUpdate, options?: HttpClientBodyOptions): Observable<TData>;
 adminStudentsGroupUpdate<TData = StudentGroupUpdate>(id: number,
    studentGroupUpdate: StudentGroupUpdate, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 adminStudentsGroupUpdate<TData = StudentGroupUpdate>(id: number,
    studentGroupUpdate: StudentGroupUpdate, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  adminStudentsGroupUpdate<TData = StudentGroupUpdate>(
    id: number,
    studentGroupUpdate: StudentGroupUpdate, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.put<TData>(
      `/api/v1/admin/students/group/${id}/`,
      studentGroupUpdate,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.put<TData>(
      `/api/v1/admin/students/group/${id}/`,
      studentGroupUpdate,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.put<TData>(
      `/api/v1/admin/students/group/${id}/`,
      studentGroupUpdate,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * A base class that inherit from `ModelViewSet` applying
 * django filter package filters and ordering filter
 */
 adminStudentsGroupDestroy<TData = void>(id: number, options?: HttpClientBodyOptions): Observable<TData>;
 adminStudentsGroupDestroy<TData = void>(id: number, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 adminStudentsGroupDestroy<TData = void>(id: number, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  adminStudentsGroupDestroy<TData = void>(
    id: number, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/v1/admin/students/group/${id}/`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/v1/admin/students/group/${id}/`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/v1/admin/students/group/${id}/`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
};

