/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zidnahum Hudaa Project API
 * OpenAPI spec version: 1.0.0
 */
import { InjectionToken, inject, type Provider } from '@angular/core';

/**
 * Embedded fallback base URL for the `api` API, resolved at generation
 * time from the OpenAPI specification's `servers` field (`''` when the
 * specification has no servers).
 */
export const API_SERVER_URL: string = '';

/**
 * Strips trailing slashes from a base URL.
 *
 * Generated routes always start with `/`, so normalizing here at the token
 * boundary guarantees `${baseUrl}${route}` can never double or drop the
 * separator between them, for either `HttpClient` services or `httpResource`
 * functions.
 */
export function normalizeBaseUrl(baseUrl: string): string {
  return baseUrl.replace(/\/+$/, '');
}

/** Context passed to a `ApiBaseUrlResolver` when it is invoked. */
export interface ApiBaseUrlResolverContext {
  /** The explicit `apiId` configured via `override.angular.baseUrl`. */
  readonly apiId: 'api';
  /** The embedded fallback server URL (`API_SERVER_URL`). */
  readonly serverUrl: string;
}

/** Resolves the runtime base URL for the `api` API. */
export type ApiBaseUrlResolver = (context: ApiBaseUrlResolverContext) => string;

/**
 * Injectable hook for resolving the `api` API's base URL at runtime
 * (e.g. from a gateway route registry). Overridden via
 * `provideApiBaseUrlResolver`; defaults to the embedded specification
 * server URL.
 */
export const API_BASE_URL_RESOLVER = new InjectionToken<ApiBaseUrlResolver>(
  'API_BASE_URL_RESOLVER',
  {
    providedIn: 'root',
    factory: (): ApiBaseUrlResolver => (context) => context.serverUrl,
  },
);

/**
 * Runtime base URL for the `api` API, composed via Angular DI.
 *
 * Precedence: a directly provided value (`provideApiBaseUrl`) wins
 * outright; otherwise the `API_BASE_URL_RESOLVER` resolver (default or
 * provided via `provideApiBaseUrlResolver`) is invoked with the embedded
 * `API_SERVER_URL` fallback. The result is always normalized.
 */
export const API_BASE_URL = new InjectionToken<string>('API_BASE_URL', {
  providedIn: 'root',
  factory: (): string => {
    const resolver = inject(API_BASE_URL_RESOLVER);
    return normalizeBaseUrl(resolver({ apiId: 'api', serverUrl: API_SERVER_URL }));
  },
});

/** Directly provides the `api` API's base URL, bypassing the resolver. */
export function provideApiBaseUrl(baseUrl: string): Provider {
  return { provide: API_BASE_URL, useValue: normalizeBaseUrl(baseUrl) };
}

/** Provides a custom resolver for the `api` API's base URL. */
export function provideApiBaseUrlResolver(resolver: ApiBaseUrlResolver): Provider {
  return { provide: API_BASE_URL_RESOLVER, useValue: resolver };
}
